// FastLED .ino export — records N seconds of the current pattern at a
// chosen frame rate and bakes every frame into a PROGMEM byte array.
// The generated sketch plays the recorded animation in a loop.
//
// This is the simplest credible MVP for "run the cube untethered": the
// sketch is just a tape-recorder, so any pattern — including class-API
// particle systems — exports as if it were prerendered video.
//
// Memory: 10×10×10 LEDs × 3 bytes × 150 frames (5 s @ 30 fps) = 450 KB.
// ESP32 has 4 MB flash by default so this fits. Users tweaking seconds
// or FPS above 10-20× that will start to hit flash limits; the panel
// surfaces the expected size.

import { invoke } from '@tauri-apps/api/core';
import { ledCount, buildCoords, type CubeSpec } from '../cubeGeometry';
import type { LoadedPattern, RenderContext, SetupContext } from '../patternApi';
import { patternUtils } from '../utils';
import { buildGammaLut, computeDuty, bakeFrame, type ColorConfig } from '../colorPipeline';
import { estimatePower, type PowerConfig } from '../power';
import { buildAddressMap, type WiringConfig } from '../wiring';
import { renderPatternFrame } from '../patternRender';

export type ExportOptions = {
  seconds: number;
  fps: number;
  dataPin: number;
  /** Sketch name stem — the file ends up at exports/{stem}_{timestamp}.ino */
  sketchStem?: string;
};

export async function exportFastLed(args: {
  pattern: LoadedPattern;
  paramValues: Record<string, any>;
  cube: CubeSpec;
  color: ColorConfig;
  power: PowerConfig;
  wiring: WiringConfig;
  options: ExportOptions;
}): Promise<{ path: string; frames: number; sizeKb: number }> {
  const { pattern, paramValues, cube, color, power, wiring, options } = args;
  const { seconds, fps, dataPin } = options;

  const N = cube.N;
  const count = ledCount(cube);
  const coords = buildCoords(cube);
  const addressMap = buildAddressMap(wiring, N);
  const gammaLut = buildGammaLut(color.gamma);

  const patternBuf = new Uint8ClampedArray(count * 3);
  const dutyBuf = new Uint8ClampedArray(count * 3);
  const streamBuf = new Uint8Array(count * 3);

  const totalFrames = Math.max(1, Math.round(seconds * fps));
  const dt = 1 / fps;

  const setupCtx: SetupContext = { N, params: paramValues };
  if (pattern.setup) pattern.setup(setupCtx);

  const rows: string[] = [];

  for (let f = 0; f < totalFrames; f++) {
    const ctx: RenderContext = {
      t: f * dt,
      dt,
      frame: f,
      N,
      params: paramValues,
      // Offline export has no live mic; beat-reactive patterns will look
      // dormant in the baked loop.
      audio: { energy: 0, low: 0, mid: 0, high: 0, beat: false },
      power: { amps: 0, watts: 0, budgetAmps: power.budgetAmps, scale: 1 },
      utils: patternUtils,
    };

    renderPatternFrame(pattern, ctx, coords, patternBuf);

    computeDuty(patternBuf, color.brightness, dutyBuf);
    const pre = estimatePower(dutyBuf, power);
    bakeFrame(patternBuf, color, gammaLut, pre.scale, addressMap, null, streamBuf);
    rows.push(formatFrameRow(streamBuf));
  }

  const sketch = buildSketch({
    N,
    count,
    dataPin,
    fps,
    totalFrames,
    paramValues,
    patternName: pattern.displayName,
    colorOrder: color.colorOrder,
    frames: rows,
  });

  const stem = sanitize(options.sketchStem ?? pattern.displayName);
  const ts = timestamp();
  const relPath = `${stem}_${ts}.ino`;
  const path = await invoke<string>('write_export', {
    relPath,
    contents: sketch,
  });

  return {
    path,
    frames: totalFrames,
    sizeKb: Math.round((sketch.length / 1024) * 10) / 10,
  };
}

/** How many flash bytes a given export will consume (approximate). */
export function estimateExportSize(N: number, seconds: number, fps: number): number {
  return N * N * N * 3 * Math.max(1, Math.round(seconds * fps));
}

function formatFrameRow(bytes: Uint8Array): string {
  let s = '';
  for (let i = 0; i < bytes.length; i++) {
    if (i > 0) s += ',';
    s += '0x' + bytes[i].toString(16).padStart(2, '0');
  }
  return s;
}

function buildSketch(args: {
  N: number;
  count: number;
  dataPin: number;
  fps: number;
  totalFrames: number;
  paramValues: Record<string, any>;
  patternName: string;
  colorOrder: string;
  frames: string[];
}): string {
  const {
    N, count, dataPin, fps, totalFrames,
    paramValues, patternName, colorOrder,
    frames,
  } = args;

  const frameBytes = count * 3;

  const paramsComment = Object.keys(paramValues)
    .map((k) => `//   ${k} = ${JSON.stringify(paramValues[k])}`)
    .join('\n');

  const framesSource = frames
    .map((row) => `  {${row}}`)
    .join(',\n');

  return `// Generated by VolumeCube — pattern: ${patternName}
// ${new Date().toISOString()}
// Baked ${totalFrames} frames at ${fps} fps (${(totalFrames / fps).toFixed(2)} s loop).
// Params:
${paramsComment}

#include <FastLED.h>

#define N           ${N}
#define LED_COUNT   ${count}
#define DATA_PIN    ${dataPin}
#define FPS         ${fps}
#define FRAME_COUNT ${totalFrames}
#define FRAME_BYTES ${frameBytes}

CRGB leds[LED_COUNT];

// Flash-resident frame data. Each row is one frame in stream order,
// ready to memcpy straight into the CRGB buffer.
const uint8_t PROGMEM frames[FRAME_COUNT][FRAME_BYTES] = {
${framesSource}
};

void setup() {
  FastLED.addLeds<WS2815, DATA_PIN, ${colorOrder}>(leds, LED_COUNT);
  FastLED.setBrightness(255);
  FastLED.clear();
  FastLED.show();
}

void loop() {
  static uint16_t f = 0;
  memcpy_P((uint8_t*)leds, frames[f], FRAME_BYTES);
  FastLED.show();
  f = (f + 1) % FRAME_COUNT;
  delay(1000 / FPS);
}
`;
}

function sanitize(name: string): string {
  return (name || 'pattern').replace(/[^a-z0-9_-]+/gi, '_').replace(/^_+|_+$/g, '') || 'pattern';
}

function timestamp(): string {
  const d = new Date();
  const pad = (n: number, w = 2) => String(n).padStart(w, '0');
  return (
    d.getFullYear() +
    pad(d.getMonth() + 1) +
    pad(d.getDate()) +
    '_' +
    pad(d.getHours()) +
    pad(d.getMinutes()) +
    pad(d.getSeconds())
  );
}
